version: '3.5'

services:
  postgres:
    image: postgres:14.0-alpine
    ports:
      - "54329:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGPASSWORD=postgres
    volumes:
      - ./docker/postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/data/postgres:/var/lib/postgresql/data

  migrant:
    build:
      context: ./
      dockerfile: docker/migrant.Dockerfile
    container_name: migrant
    command: ["./migrate"]